export const PATH = {
    NotFound: "*",
    UnAuthorize: "/un-authorize",
    Forbidden: "forbidden",
    Login: "/login",
    Register: "/register",
    Home: "/home",
    VerifyOTP: "/verify-otp",
    VerifyFailure: "/verify-failure",
    MentorApplication: "/mentor/applications/status",
    MentorDashboard: "/mentor/dashboard",
    LearnerDashboard: "/learner/dashboard",
    AdminDashboard: "/admin/dashboard",
    MentorViewCourses: "/mentor/my-courses",
    MentorAddCourse: "/mentor/my-courses/add",
    MentorViewCourseDetail: "/mentor/my-courses/:id",
    MentorViewResources: "/mentor/my-resources",
    MentorAddResource: "/mentor/my-resources/add",
    MentorSessionManagement: "/mentor/mentoring-sessions",
};
